# -*- coding: utf-8 -*-
"""Encryption.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16C7uG-4wP2GwnTOfoGphP5po93zC9mSM
"""

# Python 3 code to demonstrate the 
# working of MD5 (string - hexadecimal)
  
import hashlib
  
# initializing string
str2hash = "harsh"
  
# encoding harsh using encode()
# then sending to md5()
result = hashlib.md5(str2hash.encode())
  
# printing the equivalent hexadecimal value.
print("The hexadecimal equivalent of hash is : ", end ="")
print(result.hexdigest())

# printing the equivalent byte value.
print("The byte equivalent of hash is : ", end ="")
print(result.digest())


#printing the clone  of the hash object.
print("The clone of hash object is : ",end="")
print(result.copy())